version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - eclipse_net

  api:
    container_name: "eclipse-api"
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      PG_HOST: db
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_PORT: 5432
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - eclipse_net
    depends_on:
      - db

networks:
  eclipse_net:
    driver: bridge
